### ISSUE TITLE
Minimized Far

### ISSUE THREAD

**Issue by pasha-zzz** [huettenhain/frc#4] opened 2024-04-29 09:36 UTC
When Far is minimized after command it stays in minimized state. Now there is BringWindowToTop call but maybe replace it with ShowWindow with SW_SHOW argument or SetForegroundWindow?

**Comment by huettenhain** [comment] 2024-04-29 10:24
Sounds good, thanks for the suggestion. I will try both and see what works.

**Comment by huettenhain** [comment] 2024-05-03 15:48
So it turns out [I already do this](https://github.com/huettenhain/frc/blob/debd2e62e35053c42d295c7b28fc383652be207f/plugin/plugin.c#L269):
```c
    HWND console = GetConsoleWindow();
    if (IsIconic(console))
        ShowWindow(console, SW_SHOW);
    BringWindowToTop(console) && SetForegroundWindow(console);
```
However, I can confirm that this does not work at all. I'll have to figure out to do it properly.

**Comment by huettenhain** [comment] 2024-05-03 17:17
Looks like just calling `ShowWindow` without any condition works fine. That said, I am having an issue with the entire restoration logic when FAR runs inside Windows Terminal now that I have to take care of.

**Comment by huettenhain** [comment] 2024-05-04 14:53
Alright, I figured out how to do it. Works in all my tests now.

**Comment by huettenhain** [comment] 2024-05-04 15:02
Fixed in [V2.3](https://github.com/huettenhain/frc/releases/tag/V2.3). I will release this on the plugring ASAP.

**Comment by pasha-zzz** [comment] 2024-05-04 20:09
> Alright, I figured out how to do it. Works in all my tests now.

Not working if ConEmu is used. Stays minimized.

**Comment by huettenhain** [comment] 2024-05-04 20:11
Dang. I only tested with Windows Terminal, I will test with ConEmu.

**Comment by huettenhain** [comment] 2024-05-05 08:34
I can reproduce this with ConEmu, but I do not know how to solve it.
- For terminal emulators, the window that needs to be restored is not the return value of `GetConsoleWindow`, but some parent window of it. In FRC, I currently solve this by calling `GetForegroundWindow` during `SetStartupInfoW` so that I have a handle to whatever the foreground window is at that time.
- While this gets me the correct window for, e.g. Windows Terminal, ConEmu behaves differently; whatever I do, I get the window `0x403FC` in the below screenshot, when really I need `0x60402`.
  ![image](https://github.com/huettenhain/frc/assets/11869704/24b452c5-1ec7-475b-a884-8d47bb247361)
- Let's say the return value of `GetForegroundWindow` is `hWnd`. Then:
  - Using `GetWindow(hWnd, GW_OWNER)` returns `NULL`.
  - Using `GetParent(hWnd)` returns `NULL` as well.
  - Using `GetAncestor(hWnd, GA_PARENT)` returns the taskbar window `#32769`.
- I simply do not know a good way to get a handle to ConEmu's actual window so that I can restore it or bring it to the top.

**Comment by huettenhain** [comment] 2024-05-05 09:07
Heureka! Enumerating them top-down does actually work for some reason. When calling the following `GetRootwindow` on `hWnd`, I get the correct window and restoring the terminal works in ConEmu:
```c
typedef struct {
    HWND leaf;
    HWND root;
    BOOL done;
} __GPWDATA;

BOOL CALLBACK EnumChildProc(HWND hWnd, LPARAM lParam) {
  __GPWDATA* gpw = (__GPWDATA*)lParam;
  if (hWnd == gpw->leaf) {
    gpw->done = TRUE;
    return FALSE;
  } else {
    EnumChildWindows(hWnd, EnumChildProc, lParam);
    return !gpw->done;
  }
}

BOOL CALLBACK EnumRootsProc(HWND hWnd, LPARAM lParam) {
  __GPWDATA* gpw = (__GPWDATA*)lParam;
  if (hWnd == gpw->leaf) {
    gpw->done = TRUE;
  } else {
    EnumChildWindows(hWnd, EnumChildProc, lParam);
  }
  if (gpw->done) {
    gpw->root = hWnd;
    return FALSE;
  } else {
    return TRUE;
  }
}

HWND GetRootWindow(HWND hWnd) {
  __GPWDATA gpw = { hWnd, NULL, FALSE };
  EnumWindows(EnumRootsProc, (LPARAM) &gpw);
  if (!gpw.done || !gpw.root)
    return hWnd;
  return gpw.root;
}
```
I will do a bit more testing and then likely release 2.4 with the fix.

**Closed as completed** 2024-05-05 09:15 UTC

**Comment by pasha-zzz** [comment] 2024-05-06 02:33
> * I simply do not know a good way to get a handle to ConEmu's actual window so that I can restore it or bring it to the top.

In 2.4 all works fine with ConEmu. But too complex method is used to find ConEmu window I think. In Far plugin try to get ConEmuHWND env variable.

**Comment by huettenhain** [comment] 2024-05-06 05:58
I know many people use ConEmu with FAR, but I would prefer not to hard-code any magic values for a specific terminal emulator. I think doing a top-down search of all windows is fine, and it works with _all_ terminal emulators I have tested: Windows Terminal, CMDer, ConEmu, PowerShell, and the default console.
